// Core model contract shared by interpreter, renderer and grader.
// Everything here must be structured-cloneable (Maps, Sets, typed arrays, plain objects)
// so a ModelState can be posted from the interpreter Web Worker to the main thread.

export type Vec3 = [number, number, number];
export type Id = number;

export interface BBox {
  min: Vec3;
  max: Vec3;
}

/** Triangle soup in GLOBAL cartesian coordinates. idx holds 3 vertex indices per triangle. */
export interface TriMesh {
  pos: Float64Array; // xyz per vertex
  idx: Uint32Array; // 3 per triangle
  /** Optional per-triangle tag. For volume shells this is the area id the triangle belongs to. */
  tag?: Uint32Array;
}

export interface Keypoint {
  id: Id;
  xyz: Vec3;
  /** KATT attributes (for KMESH) */
  attrs?: Partial<EntityAttrs>;
}

export type LineKind = 'straight' | 'arc' | 'poly';

export interface LineMeshCtl {
  /** explicit number of divisions (LESIZE NDIV) */
  ndiv?: number;
  /** explicit element size (LESIZE SIZE) */
  size?: number;
  /** spacing ratio (LESIZE SPACE) */
  space?: number;
}

export interface EntityAttrs {
  type: Id;
  mat: Id;
  real: Id;
  secnum: Id;
  esys: Id;
}

export interface Line {
  id: Id;
  kps: [Id, Id];
  kind: LineKind;
  /** Canonical polyline from kps[0] to kps[1] (inclusive). Shared by every area that uses this line. */
  pts: Vec3[];
  /** For arcs: circle centre, unit axis (right-hand rule from kp0 to kp1), radius. */
  arc?: { center: Vec3; axis: Vec3; radius: number };
  length: number;
  mesh?: LineMeshCtl;
  attrs?: Partial<EntityAttrs> & { kb?: Id; ke?: Id };
}

export type Surface =
  | { kind: 'plane'; origin: Vec3; normal: Vec3; u: Vec3; v: Vec3 }
  | { kind: 'cyl'; origin: Vec3; axis: Vec3; radius: number; ref: Vec3 }
  | { kind: 'sphere'; center: Vec3; radius: number }
  | { kind: 'free' }; // tessellation is authoritative

export interface Area {
  id: Id;
  /** loops[0] is the outer loop; others are holes. Signed line ids: negative = traversed reversed. */
  loops: number[][];
  surface: Surface;
  /** Tessellation in global coordinates. Triangle winding follows the area normal. */
  tess: TriMesh;
  area: number;
  centroid: Vec3;
  attrs?: Partial<EntityAttrs>;
  esize?: number;
}

/** Meshing hint recorded when a volume is generated by a sweep/primitive. Lost after Booleans. */
export type VolumeGen =
  | { kind: 'prism'; dir: Vec3 } // translational sweep (BLOCK, CYL4, VEXT, VOFFST ...)
  | { kind: 'revolve'; axisPt: Vec3; axisDir: Vec3; angleDeg: number; srcArea: Id }
  | { kind: 'drag'; srcArea: Id; path: Id[] };

export interface Volume {
  id: Id;
  areas: Id[];
  /** areaFlip[i] = true when area i's tessellation normal points INTO this volume. */
  areaFlip: boolean[];
  /** Closed, outward-oriented shell (concatenation of oriented area tessellations). tag = area id. */
  tess: TriMesh;
  volume: number;
  bbox: BBox;
  centroid: Vec3;
  attrs?: Partial<EntityAttrs>;
  esize?: number;
  gen?: VolumeGen;
}

export interface Node {
  id: Id;
  xyz: Vec3;
}

export type ElemShape = 'hex' | 'wedge' | 'pyramid' | 'tet' | 'quad' | 'tri' | 'line' | 'point';

export interface Element {
  id: Id;
  /** Corner nodes first (ANSYS order), then midside nodes for quadratic elements. */
  nodes: Id[];
  shape: ElemShape;
  type: Id;
  mat: Id;
  real: Id;
  secnum: Id;
  esys: Id;
  /** Solid-model entity this element was meshed from (undefined for direct generation). */
  parent?: { kind: 'volu' | 'area' | 'line' | 'kp'; id: Id };
}

export type ElemCategory = 'solid' | 'shell' | 'beam' | 'link' | 'spring' | 'mass' | 'surf';

export interface ElementType {
  id: Id;
  ename: string; // e.g. "SOLID185"
  category: ElemCategory;
  keyopts: Record<number, number>;
}

export interface Material {
  id: Id;
  props: Record<string, number>; // EX, PRXY, NUXY, DENS, ...
}

export interface RealSet {
  id: Id;
  values: number[];
}

export interface Section {
  id: Id;
  type: string; // BEAM, SHELL, LINK, ...
  subtype: string; // RECT, CSOLID, I, HREC, CTUBE ... ('' for SHELL)
  name?: string;
  /** SECDATA values (BEAM RECT: B,H; SHELL: thickness, mat, angle, nip per layer flattened as first layer). */
  data: number[];
  offset?: string;
}

export type EntityKind = 'kp' | 'line' | 'area' | 'volu' | 'node' | 'elem';

export interface Component {
  name: string;
  kind: EntityKind;
  ids: Id[];
}

export type Selection = Record<EntityKind, Set<Id>>;

export type DofLab = 'UX' | 'UY' | 'UZ' | 'ROTX' | 'ROTY' | 'ROTZ' | 'TEMP';
export type ForceLab = 'FX' | 'FY' | 'FZ' | 'MX' | 'MY' | 'MZ' | 'HEAT';

/** Nodal constraint or force, or element-face pressure. Solid-model loads are transferred into these. */
export interface BCRecord {
  kind: 'D' | 'F' | 'SF';
  /** node id for D/F, element id for SF */
  target: Id;
  lab: string; // DofLab | ForceLab | 'PRES'
  value: number;
  /** element face number for SF */
  face?: number;
  /** command that produced it, e.g. 'D', 'DA', 'FK' */
  src: string;
}

/** Load applied to a solid-model entity; transferred to nodes after meshing. */
export interface SolidLoad {
  cmd: 'DK' | 'DL' | 'DA' | 'FK' | 'SFA' | 'SFL';
  entity: Id;
  lab: string;
  value: number;
  line: number;
}

export interface WorkingPlane {
  origin: Vec3;
  /** WP x, y, z(normal) unit axes in global coordinates. */
  axes: [Vec3, Vec3, Vec3];
}

export interface CoordSys {
  id: Id;
  /** 0 cartesian, 1 cylindrical, 2 spherical */
  type: 0 | 1 | 2;
  origin: Vec3;
  axes: [Vec3, Vec3, Vec3];
}

export interface CurrentSettings extends EntityAttrs {
  csys: Id;
  esize: number; // 0 = unset
  esizeNdiv: number; // 0 = unset
  mshape: 0 | 1; // 0 hex/quad, 1 tet/tri
  mshape3d: boolean;
  mshkey: 0 | 1 | 2; // 0 free, 1 mapped, 2 mapped if possible
  seltol: number;
}

export type Processor = 'BEGIN' | 'PREP7' | 'SOLU' | 'POST1';

export interface ModelState {
  title: string;
  processor: Processor;
  kps: Map<Id, Keypoint>;
  lines: Map<Id, Line>;
  areas: Map<Id, Area>;
  volus: Map<Id, Volume>;
  nodes: Map<Id, Node>;
  elems: Map<Id, Element>;
  etypes: Map<Id, ElementType>;
  mats: Map<Id, Material>;
  reals: Map<Id, RealSet>;
  secs: Map<Id, Section>;
  comps: Map<string, Component>;
  sel: Selection;
  bcs: BCRecord[];
  solidLoads: SolidLoad[];
  /** Global acceleration (ACEL). null when never set. */
  acel: Vec3 | null;
  params: Map<string, number | string>;
  cur: CurrentSettings;
  csyss: Map<Id, CoordSys>;
  wp: WorkingPlane;
  /** NUMSTR starting numbers */
  numstr: Partial<Record<EntityKind, number>>;
  /** node id -> owning solid-model entity key ("V3", "A7", "L2", "K1"), used for node sharing rules */
  nodeOwner: Map<Id, string>;
  /** canonical command names executed, in first-use order (for required/forbidden checks & badges) */
  commandsUsed: string[];
  /** max *DO iteration count seen in a single loop (for achievements) */
  maxLoopIterations: number;
}
