// Argument documentation for signature help and value completion in the editor.
// Lookup order: per-command override ("CMD.ARG") -> generic by argument name -> numbered-argument patterns.

export interface Choice {
  v: string;
  d: string;
}

export interface ArgDoc {
  desc: string;
  choices?: Choice[];
}

const ENTITY_LIST = 'or ALL (all selected), or a component name';

const SEL_TYPE: Choice[] = [
  { v: 'S', d: 'Select a new set (default)' },
  { v: 'R', d: 'Reselect from the current set' },
  { v: 'A', d: 'Add to the current set' },
  { v: 'U', d: 'Unselect from the current set' },
  { v: 'ALL', d: 'Select everything' },
  { v: 'NONE', d: 'Select nothing' },
  { v: 'INVE', d: 'Invert the current set' },
];
const SEL_TYPE_SHORT = SEL_TYPE.slice(0, 4);
const XYZ: Choice[] = [
  { v: 'X', d: 'X (or R in CSYS,1)' },
  { v: 'Y', d: 'Y (or θ in degrees in CSYS,1)' },
  { v: 'Z', d: 'Z' },
];
const DOFS: Choice[] = [
  { v: 'ALL', d: 'All structural DOFs' },
  { v: 'UX', d: 'Translation X' },
  { v: 'UY', d: 'Translation Y' },
  { v: 'UZ', d: 'Translation Z' },
  { v: 'ROTX', d: 'Rotation about X (beams/shells)' },
  { v: 'ROTY', d: 'Rotation about Y (beams/shells)' },
  { v: 'ROTZ', d: 'Rotation about Z (beams/shells)' },
];
const FORCES: Choice[] = [
  { v: 'FX', d: 'Force X' },
  { v: 'FY', d: 'Force Y' },
  { v: 'FZ', d: 'Force Z' },
  { v: 'MX', d: 'Moment about X' },
  { v: 'MY', d: 'Moment about Y' },
  { v: 'MZ', d: 'Moment about Z' },
];
const ENTITIES: Choice[] = [
  { v: 'VOLU', d: 'Volumes' },
  { v: 'AREA', d: 'Areas' },
  { v: 'LINE', d: 'Lines' },
  { v: 'KP', d: 'Keypoints' },
  { v: 'ELEM', d: 'Elements' },
  { v: 'NODE', d: 'Nodes' },
];
const ELEMENTS: Choice[] = [
  { v: 'SOLID185', d: '8-node brick (hex/wedge/tet)' },
  { v: 'SOLID186', d: '20-node quadratic brick' },
  { v: 'SOLID187', d: '10-node quadratic tet' },
  { v: 'BEAM188', d: '2-node beam, needs SECTYPE/SECDATA' },
  { v: 'BEAM189', d: '3-node quadratic beam' },
  { v: 'SHELL181', d: '4-node shell, thickness via SECTYPE,,SHELL' },
  { v: 'SHELL281', d: '8-node quadratic shell' },
  { v: 'COMBIN14', d: 'Spring-damper, R = stiffness' },
  { v: 'MASS21', d: 'Point mass (KEYOPT,n,3,2 → R = mass)' },
  { v: 'LINK180', d: 'Truss / spar' },
  { v: 'SURF154', d: 'Surface effect (pressure)' },
  { v: 'MPC184', d: 'Rigid link / MPC' },
];
const MP_LABELS: Choice[] = [
  { v: 'EX', d: "Young's modulus" },
  { v: 'PRXY', d: "Major Poisson's ratio" },
  { v: 'NUXY', d: "Minor Poisson's ratio" },
  { v: 'DENS', d: 'Mass density' },
  { v: 'GXY', d: 'Shear modulus' },
  { v: 'ALPX', d: 'Thermal expansion coefficient' },
  { v: 'DMPR', d: 'Constant structural damping ratio' },
];
const PNUM_LABELS: Choice[] = [
  { v: 'KP', d: 'Keypoint numbers' },
  { v: 'LINE', d: 'Line numbers' },
  { v: 'AREA', d: 'Area numbers' },
  { v: 'VOLU', d: 'Volume numbers' },
  { v: 'NODE', d: 'Node numbers' },
  { v: 'ELEM', d: 'Element numbers' },
  { v: 'TYPE', d: 'Colour by element type' },
  { v: 'MAT', d: 'Colour by material' },
  { v: 'SECN', d: 'Colour by section' },
];
const KEEP: Choice[] = [
  { v: 'DELETE', d: 'Delete this input after the operation (default)' },
  { v: 'KEEP', d: 'Keep this input' },
];

const GENERIC: Record<string, ArgDoc> = {
  // coordinates
  X: { desc: 'X coordinate in the active coordinate system (R in CSYS,1)' },
  Y: { desc: 'Y coordinate (θ in degrees in CSYS,1)' },
  Z: { desc: 'Z coordinate' },
  X1: { desc: 'Start X in working-plane coordinates' },
  X2: { desc: 'End X in working-plane coordinates' },
  Y1: { desc: 'Start Y in working-plane coordinates' },
  Y2: { desc: 'End Y in working-plane coordinates' },
  Z1: { desc: 'Start Z in working-plane coordinates' },
  Z2: { desc: 'End Z in working-plane coordinates' },
  XCORNER: { desc: 'WP X of the corner the rectangle grows from' },
  YCORNER: { desc: 'WP Y of the corner' },
  XCENTER: { desc: 'WP X of the centre' },
  YCENTER: { desc: 'WP Y of the centre' },
  WIDTH: { desc: 'Size along WP X (negative grows towards -X)' },
  HEIGHT: { desc: 'Size along WP Y (negative grows towards -Y)' },
  DEPTH: { desc: 'Extrusion along WP Z; 0 or blank creates an area only' },
  RAD1: { desc: 'Inner or outer radius (either order); 0 = solid' },
  RAD2: { desc: 'Other radius; blank or equal to RAD1 = solid' },
  THETA1: { desc: 'Start angle in degrees (default 0)' },
  THETA2: { desc: 'End angle in degrees (default 360)' },
  RBOT: { desc: 'Radius at Z1' },
  RTOP: { desc: 'Radius at Z2 (0 = pointed cone)' },
  XOFF: { desc: 'Move the WP origin along WP X' },
  YOFF: { desc: 'Move the WP origin along WP Y' },
  ZOFF: { desc: 'Move the WP origin along WP Z (cumulative: undo it later!)' },
  THXY: { desc: 'Rotation about Z, degrees (first)' },
  THYZ: { desc: 'Rotation about the new X, degrees (second)' },
  THZX: { desc: 'Rotation about the new Y, degrees (third)' },
  XC: { desc: 'Origin X of the new system' },
  YC: { desc: 'Origin Y' },
  ZC: { desc: 'Origin Z' },
  DX: { desc: 'Offset in X (active CSYS) applied per copy' },
  DY: { desc: 'Offset in Y (degrees in CSYS,1) applied per copy' },
  DZ: { desc: 'Offset in Z applied per copy' },
  // entity numbers
  NPT: { desc: 'Keypoint number; blank = lowest free number' },
  NODE: { desc: `Node number, ${ENTITY_LIST}` },
  NODE1: { desc: `First node, ${ENTITY_LIST}` },
  NODE2: { desc: 'Last node (default NODE1)' },
  NP1: { desc: `First keypoint, ${ENTITY_LIST}` },
  NP2: { desc: 'Last keypoint (default NP1)' },
  NL1: { desc: `First line, ${ENTITY_LIST}` },
  NL2: { desc: 'Last line (default NL1)' },
  NA1: { desc: `First area, ${ENTITY_LIST}` },
  NA2: { desc: 'Last area (default NA1)' },
  NV1: { desc: `First volume, ${ENTITY_LIST}` },
  NV2: { desc: 'Last volume (default NV1)' },
  NINC: { desc: 'Increment between N1 and N2 (default 1)' },
  IEL1: { desc: `First element, ${ENTITY_LIST}` },
  IEL2: { desc: 'Last element (default IEL1)' },
  IEINC: { desc: 'Element increment (default 1)' },
  KPOI: { desc: `Keypoint, ${ENTITY_LIST}` },
  LINE: { desc: `Line, ${ENTITY_LIST}` },
  AREA: { desc: `Area, ${ENTITY_LIST}` },
  ELEM: { desc: `Element, ${ENTITY_LIST}` },
  NAREA: { desc: 'Area to offset' },
  NV: { desc: 'Volume(s) to divide' },
  NA: { desc: 'Cutting area' },
  // generation
  ITIME: { desc: 'Number of sets INCLUDING the original (2 = one copy)' },
  KINC: { desc: 'Numbering increment between sets; 0 = lowest free numbers' },
  NOELEM: { desc: '0 = copy attached mesh too, 1 = geometry only' },
  IMOVE: { desc: '0 = copy, 1 = move instead of copy' },
  INC: { desc: 'Number increment between generated sets' },
  NFILL: { desc: 'How many to fill between the two (default: all numbers between)' },
  NSTRT: { desc: 'First number to assign' },
  SPACE: { desc: 'Spacing ratio last/first (default 1 = uniform)' },
  MINC: { desc: 'Material number increment per set' },
  TINC: { desc: 'Element type increment per set' },
  RINC: { desc: 'Real constant set increment per set' },
  CINC: { desc: 'Element coordinate system increment per set' },
  SINC: { desc: 'Section number increment per set' },
  // attributes
  ITYPE: { desc: 'Element type reference number' },
  MAT: { desc: 'Material reference number' },
  REAL: { desc: 'Real constant set number' },
  TYPE: { desc: 'Element type number' },
  ESYS: { desc: 'Element coordinate system' },
  SECNUM: { desc: 'Section number' },
  SECN: { desc: 'Section number' },
  SECID: { desc: 'Section identification number' },
  NSET: { desc: 'Real constant set number' },
  KNUM: { desc: 'KEYOPT number (1-18)' },
  VALUE: { desc: 'Value' },
  VALUE2: { desc: 'Second value (imaginary part / end value)' },
  KB: { desc: 'Orientation keypoint at the line start (beams)' },
  KE: { desc: 'Orientation keypoint at the line end (beams)' },
  // mesh
  SIZE: { desc: 'Element edge length' },
  NDIV: { desc: 'Number of element divisions (overrides SIZE)' },
  ANGSIZ: { desc: 'Element arc angle in degrees (curved lines)' },
  // selection
  Type: { desc: 'Selection type', choices: SEL_TYPE },
  Item: { desc: 'What to select by (blank = entity number)' },
  Comp: { desc: 'Component of the item', choices: XYZ },
  VMIN: { desc: 'Minimum value of the range' },
  VMAX: { desc: 'Maximum value (default VMIN; a small tolerance is applied)' },
  VINC: { desc: 'Value increment (entity numbers only)' },
  KABS: { desc: '0 = signed values, 1 = absolute values' },
  NKEY: { desc: '0 = interior only, 1 = include boundary' },
  Entity: { desc: 'Entity type', choices: ENTITIES },
  Cname: { desc: 'Component name (up to 32 characters, starts with a letter)' },
  Name: { desc: 'Component / section name' },
  // loads
  Lab: { desc: 'Degree of freedom label', choices: DOFS },
  VALUE_D: { desc: 'Constraint value (0 = fixed)' },
  NEND: { desc: 'Last node of a range (with NINC)' },
  // misc
  Par: { desc: 'Parameter name (up to 32 characters)' },
  KCN: { desc: 'Coordinate system number: 0 cartesian, 1 cylindrical, 2 spherical, 4 working plane, ≥11 local' },
  KCS: { desc: 'System type', choices: [{ v: '0', d: 'Cartesian' }, { v: '1', d: 'Cylindrical' }, { v: '2', d: 'Spherical' }] },
  SEPO: { desc: 'Blank = shared boundary, SEPO = separate entities' },
  KEEP1: { desc: 'First input', choices: KEEP },
  KEEP2: { desc: 'Second input', choices: KEEP },
  KEEPV: { desc: 'Volumes', choices: KEEP },
  KEEPA: { desc: 'Areas', choices: KEEP },
  KSWP: { desc: '0 = this entity only, 1 = also delete unattached lower entities' },
  ARC: { desc: 'Arc length in degrees (default 360; positive = right-hand rule about the axis)' },
  NSEG: { desc: 'Number of segments (default: one per ≤90°)' },
  PAX1: { desc: 'Keypoint at the start of the rotation axis' },
  PAX2: { desc: 'Keypoint at the end of the rotation axis' },
  TOLER: { desc: 'Coincidence tolerance (default 1E-4)' },
  Label: { desc: 'Item label' },
  Title: { desc: 'Title text (rest of the line)' },
  WN: { desc: 'Window number (1)' },
  XV: { desc: 'View-point X (camera looks from here towards the origin)' },
  YV: { desc: 'View-point Y' },
  ZV: { desc: 'View-point Z' },
  Ncomp: { desc: 'Symmetry plane normal', choices: [{ v: 'X', d: 'Reflect X (about the YZ plane)' }, { v: 'Y', d: 'Reflect Y' }, { v: 'Z', d: 'Reflect Z' }] },
  RATIO: { desc: 'Where to split along the line (0..1, default 0.5)' },
  Toler: { desc: 'Absolute tolerance (blank = default)' },
  IEL: { desc: 'Element number' },
  IINC: { desc: 'Element number increment between sets' },
  STLOC: { desc: 'Attribute to change: MAT, TYPE, REAL, SECN or ESYS' },
  I1: { desc: 'New attribute value' },
  NSIDES: { desc: 'Number of sides' },
  RADIUS: { desc: 'Circumscribed radius' },
  THETA: { desc: 'Rotation of the first vertex, degrees' },
  Nlist: { desc: 'ALL (selected nodes) or a component' },
  XEDGE1: { desc: 'WP X of one end of the diameter' },
  YEDGE1: { desc: 'WP Y of one end of the diameter' },
  XEDGE2: { desc: 'WP X of the other end' },
  YEDGE2: { desc: 'WP Y of the other end' },
  XL: { desc: 'Origin X in the active system' },
  YL: { desc: 'Origin Y in the active system' },
  ZL: { desc: 'Origin Z in the active system' },
  Comment: { desc: 'Text to print' },
  ARKEY: { desc: '0 = any line selected, 1 = all lines selected' },
  LSKEY: { desc: '0 = any keypoint selected, 1 = both keypoints selected' },
  VLKEY: { desc: '0 = any area selected, 1 = all areas selected' },
  IMAX: { desc: 'Rows' },
  JMAX: { desc: 'Columns (default 1)' },
  KMAX: { desc: 'Planes (default 1)' },
};

const OVERRIDES: Record<string, ArgDoc> = {
  'POLYGON.X1': { desc: 'X of point 1' },
  'POLYGON.Y1': { desc: 'Y of point 1' },
  'POLYGON.X2': { desc: 'X of point 2' },
  'POLYGON.Y2': { desc: 'Y of point 2' },
  'WPAVE.X1': { desc: 'X of point 1' },
  'WPAVE.Y1': { desc: 'Y of point 1' },
  'WPAVE.Z1': { desc: 'Z of point 1' },
  'WPAVE.X2': { desc: 'X of point 2' },
  'WPAVE.Y2': { desc: 'Y of point 2' },
  'WPAVE.Z2': { desc: 'Z of point 2' },
  '/CLEAR.Read': { desc: 'NOSTART = do not re-read the start-up file' },
  '*ELSEIF.Oper1': { desc: 'Comparison: EQ NE LT GT LE GE ABLT ABGT' },
  '*GET.IT2NUM': { desc: 'Second item qualifier (rarely needed)' },
  '/ESHAPE.KEY': { desc: '1 = show sections' },
  'SECOFFSET.Location': { desc: 'Section offset', choices: [{ v: 'CENT', d: 'Centroid' }, { v: 'SHRC', d: 'Shear centre' }, { v: 'ORIGIN', d: 'Section origin' }, { v: 'USER', d: 'User offsets' }, { v: 'MID', d: 'Shell mid-plane' }, { v: 'TOP', d: 'Shell top' }, { v: 'BOT', d: 'Shell bottom' }] },
  'NUMMRG.GTOLER': { desc: 'Solid-model tolerance (blank = default)' },
  'NUMMRG.Action': { desc: 'Blank = merge (LOW keeps lower numbers)' },
  'NUMMRG.Switch': { desc: 'Blank (keep lower numbers)' },
  'NSLE.NodeType': { desc: 'Which element nodes', choices: [{ v: 'ALL', d: 'All nodes (default)' }, { v: 'CORNER', d: 'Corner nodes only' }] },
  'ESLN.EKEY': { desc: '0 = element has any selected node, 1 = all its nodes selected' },
  'ESLN.NodeType': { desc: 'Node subset (ALL)' },
  'DK.KEXPND': { desc: 'Expand to nodes between keypoints (ignored)' },
  'SFE.KVAL': { desc: 'Real (blank) or imaginary part' },
  'RPRISM.LSIDE': { desc: 'Side length (alternative to MAJRAD)' },
  'RPRISM.MAJRAD': { desc: 'Circumscribed radius' },
  'RPRISM.MINRAD': { desc: 'Inscribed radius' },
  'BOPTN.Value': { desc: 'Option value, e.g. YES / NO' },
  'LDIV.PDIV': { desc: 'Number for the new keypoint (blank = next free)' },
  'LDIV.KEEP': { desc: '0 = modify the line in place' },
  'SFL.VALI': { desc: 'Value at the line start' },
  'SFL.VALJ': { desc: 'Value at the line end (default VALI)' },
  'VSUM.LAB': { desc: 'Blank (report totals)' },
  'ASUM.LAB': { desc: 'Blank (report totals)' },
  '*AFUN.Lab': { desc: 'Angle units', choices: [{ v: 'DEG', d: 'Degrees' }, { v: 'RAD', d: 'Radians (default)' }] },
  '*DIM.Type': { desc: 'Parameter type', choices: [{ v: 'ARRAY', d: 'Numeric array' }] },
  'BOPTN.Lab': { desc: 'Option', choices: [{ v: 'KEEP', d: 'Keep Boolean inputs (Value YES/NO)' }, { v: 'DEFA', d: 'Reset to defaults' }] },
  'DDELE.Lab': { desc: 'DOF to delete', choices: DOFS },
  'FDELE.Lab': { desc: 'Force to delete', choices: FORCES.concat([{ v: 'ALL', d: 'All forces' }]) },
  'SF.Lab': { desc: 'Surface load', choices: [{ v: 'PRES', d: 'Pressure' }] },
  'SFL.Lab': { desc: 'Surface load', choices: [{ v: 'PRES', d: 'Pressure' }] },
  // primitives
  'BLOCK.X1': { desc: 'Start X (BLOCK takes coordinate RANGES: X1,X2,Y1,Y2,Z1,Z2)' },
  'RECTNG.X1': { desc: 'Start X (RECTNG takes ranges: X1,X2,Y1,Y2)' },
  'CYL4.XCENTER': { desc: 'WP X of the circle centre' },
  'CYL4.RAD1': { desc: 'Radius (RAD1/RAD2 are inner/outer in either order)' },
  'CYL4.THETA1': { desc: 'Start angle of RAD1 edge (default 0)' },
  'CYL4.RAD2': { desc: 'Second radius; blank = solid circle' },
  'CYL4.THETA2': { desc: 'End angle (default 360)' },
  'CYL4.DEPTH': { desc: 'Height along WP Z; blank = circle AREA only' },
  'CYLIND.Z1': { desc: 'Start Z of the cylinder (WP)' },
  'CYLIND.Z2': { desc: 'End Z of the cylinder (WP)' },
  'SPHERE.RAD1': { desc: 'Outer radius (or inner)' },
  'SPHERE.RAD2': { desc: 'Other radius (hollow sphere)' },
  // geometry
  'K.NPT': { desc: 'Keypoint number; blank = lowest free number' },
  'L.P1': { desc: 'Keypoint at the start of the line' },
  'L.P2': { desc: 'Keypoint at the end of the line' },
  'L.NDIV': { desc: 'Element divisions for this line (optional)' },
  'LARC.P1': { desc: 'Keypoint at the start of the arc' },
  'LARC.P2': { desc: 'Keypoint at the end of the arc' },
  'LARC.PC': { desc: 'Keypoint on the centre side, defines the arc plane' },
  'LARC.RAD': { desc: 'Radius; blank = arc through P1, PC, P2' },
  'CIRCLE.PCENT': { desc: 'Centre keypoint' },
  'CIRCLE.RAD': { desc: 'Radius (blank = distance to PZERO)' },
  'CIRCLE.PAXIS': { desc: 'Keypoint on the axis (default: normal to the WP)' },
  'CIRCLE.PZERO': { desc: 'Keypoint defining the θ = 0 direction' },
  'V.P1': { desc: 'Bottom-face keypoint 1 (P1-P4 bottom, P5-P8 top in the same order)' },
  'VOFFST.DIST': { desc: 'Distance along the area normal (negative = opposite side)' },
  'VOFFST.KINC': { desc: 'Keypoint increment for the new keypoints' },
  'VEXT.DX': { desc: 'Extrusion offset X (offset, NOT a target coordinate)' },
  'VEXT.DY': { desc: 'Extrusion offset Y' },
  'VEXT.DZ': { desc: 'Extrusion offset Z' },
  'VEXT.RX': { desc: 'Scale factor X (ignored by the trainer)' },
  'VEXT.RY': { desc: 'Scale factor Y (ignored)' },
  'VEXT.RZ': { desc: 'Scale factor Z (ignored)' },
  'VSBV.NV1': { desc: `Volume to subtract FROM, ${ENTITY_LIST}` },
  'VSBV.NV2': { desc: `Volume(s) to subtract (tool), ${ENTITY_LIST}` },
  'ASBA.NA1': { desc: `Area to subtract FROM, ${ENTITY_LIST}` },
  'ASBA.NA2': { desc: `Area(s) to subtract, ${ENTITY_LIST}` },
  'VSWEEP.VNUM': { desc: 'Volume to sweep (or ALL)' },
  'VSWEEP.SRCA': { desc: 'Source area (optional)' },
  'VSWEEP.TRGA': { desc: 'Target area (optional)' },
  'VSWEEP.LSMO': { desc: 'Line smoothing (ignored)' },
  // attributes
  'ET.ITYPE': { desc: 'Element type number you will use with TYPE' },
  'ET.Ename': { desc: 'Element name or number', choices: ELEMENTS },
  'ET.INOPR': { desc: 'Suppress output (ignored)' },
  'KEYOPT.ITYPE': { desc: 'Element type number' },
  'KEYOPT.KNUM': { desc: 'Key option number, e.g. 3 for MASS21, 2 for COMBIN14' },
  'KEYOPT.VALUE': { desc: 'Key option value, e.g. MASS21 K3=2 (3-D mass, no rotary inertia)' },
  'MP.Lab': { desc: 'Material property', choices: MP_LABELS },
  'MP.MAT': { desc: 'Material number' },
  'MP.C0': { desc: 'Property value (constant term)' },
  'R.NSET': { desc: 'Real constant set number (use with REAL)' },
  'R.R1': { desc: 'First constant: COMBIN14 stiffness K, MASS21 (K3=2) mass, SHELL63 thickness' },
  'R.R2': { desc: 'Second constant: COMBIN14 damping CV1' },
  'SECTYPE.SECID': { desc: 'Section number (use with SECNUM / LATT)' },
  'SECTYPE.Type': { desc: 'Section family', choices: [{ v: 'BEAM', d: 'Beam cross-section' }, { v: 'SHELL', d: 'Shell thickness / layers' }, { v: 'LINK', d: 'Truss area' }, { v: 'PIPE', d: 'Pipe' }] },
  'SECTYPE.Subtype': { desc: 'Beam shape', choices: [{ v: 'RECT', d: 'Rectangle: SECDATA,B,H' }, { v: 'CSOLID', d: 'Solid circle: SECDATA,R' }, { v: 'CTUBE', d: 'Tube: SECDATA,Ri,Ro' }, { v: 'I', d: 'I-section: W1,W2,W3,t1,t2,t3' }, { v: 'HREC', d: 'Hollow rectangle' }, { v: 'L', d: 'Angle' }, { v: 'T', d: 'T-section' }, { v: 'CHAN', d: 'Channel' }] },
  'SECTYPE.Name': { desc: 'Optional section name' },
  'SECTYPE.REFINEKEY': { desc: 'Section mesh refinement (ignored)' },
  'SECDATA.VAL1': { desc: 'RECT: B (width along element y) · SHELL: thickness · CSOLID: radius' },
  'SECDATA.VAL2': { desc: 'RECT: H (depth along element z) · SHELL: material' },
  'SECDATA.VAL3': { desc: 'Third dimension (section-dependent)' },
  'LATT.MAT': { desc: 'Material for the selected lines' },
  'LATT.REAL': { desc: 'Real set for the selected lines' },
  'LATT.TYPE': { desc: 'Element type for the selected lines' },
  'LATT.SECNUM': { desc: 'Section for the selected lines (7th field!)' },
  'VATT.MAT': { desc: 'Material for the selected volumes' },
  'AATT.MAT': { desc: 'Material for the selected areas' },
  'AATT.SECN': { desc: 'Section for the selected areas (shell thickness)' },
  // mesh
  'ESIZE.SIZE': { desc: 'Global element edge length (divisions = ceil(length / SIZE))' },
  'ESIZE.NDIV': { desc: 'Divisions per line when SIZE is blank' },
  'LESIZE.NL1': { desc: 'Line number, ALL (selected lines) or a component' },
  'LESIZE.SIZE': { desc: 'Element edge length on these lines' },
  'LESIZE.NDIV': { desc: 'Exact number of divisions on these lines' },
  'AESIZE.ANUM': { desc: 'Area number or ALL' },
  'AESIZE.SIZE': { desc: 'Element size inside these areas' },
  'MSHAPE.KEY': { desc: 'Element shape', choices: [{ v: '0', d: 'Quads / hexes' }, { v: '1', d: 'Triangles / tets' }] },
  'MSHAPE.Dimension': { desc: 'Applies to', choices: [{ v: '3D', d: 'Volume meshing' }, { v: '2D', d: 'Area meshing' }] },
  'MSHKEY.KEY': { desc: 'Mesher', choices: [{ v: '0', d: 'Free' }, { v: '1', d: 'Mapped' }, { v: '2', d: 'Mapped if possible' }] },
  // direct generation
  'N.NODE': { desc: 'Node number; blank = lowest free number' },
  'NGEN.ITIME': { desc: 'Number of sets including the original (2 = one copy)' },
  'NGEN.INC': { desc: 'Node number increment between sets (required)' },
  'NFILL.NODE1': { desc: 'First end node (existing)' },
  'NFILL.NODE2': { desc: 'Second end node (existing)' },
  'NFILL.ITIME': { desc: 'Repeat the fill this many times' },
  'NFILL.INC': { desc: 'Node increment between repeated fills' },
  'E.I': { desc: 'Node I (uses the active TYPE, MAT, REAL, SECNUM)' },
  'E.J': { desc: 'Node J' },
  'E.K': { desc: 'Node K (solids/shells; beams: optional orientation node)' },
  'E.L': { desc: 'Node L' },
  'E.M': { desc: 'Node M (top face of a brick: above I)' },
  'EGEN.ITIME': { desc: 'Number of sets including the original' },
  'EGEN.NINC': { desc: 'Node number increment between sets' },
  'EGEN.DX': { desc: 'Create missing nodes offset by DX (optional)' },
  'NUMMRG.Label': { desc: 'What to merge', choices: [{ v: 'NODE', d: 'Coincident nodes' }, { v: 'KP', d: 'Coincident keypoints (+ lines, areas)' }, { v: 'ELEM', d: 'Duplicate elements' }, { v: 'ALL', d: 'All of the above' }] },
  'NUMCMP.Label': { desc: 'What to renumber', choices: [{ v: 'ALL', d: 'Everything' }, { v: 'NODE', d: 'Nodes' }, { v: 'ELEM', d: 'Elements' }, { v: 'KP', d: 'Keypoints' }, { v: 'LINE', d: 'Lines' }, { v: 'AREA', d: 'Areas' }, { v: 'VOLU', d: 'Volumes' }] },
  'NUMSTR.Label': { desc: 'Entity whose numbering starts at VALUE', choices: ENTITIES },
  // selection
  'NSEL.Item': { desc: 'Select nodes by', choices: [{ v: 'LOC', d: 'Location (then Comp X/Y/Z, VMIN, VMAX)' }, { v: 'NODE', d: 'Node number' }, { v: 'EXT', d: 'Exterior nodes' }, { v: 'D', d: 'Nodes with constraints' }, { v: 'F', d: 'Nodes with forces' }] },
  'ESEL.Item': { desc: 'Select elements by', choices: [{ v: 'TYPE', d: 'Element type number' }, { v: 'MAT', d: 'Material number' }, { v: 'REAL', d: 'Real set' }, { v: 'SEC', d: 'Section number' }, { v: 'ENAME', d: 'Element name/number (e.g. 185)' }, { v: 'CENT', d: 'Centroid location (Comp X/Y/Z)' }, { v: 'ELEM', d: 'Element number' }] },
  'KSEL.Item': { desc: 'Select keypoints by', choices: [{ v: 'LOC', d: 'Location' }, { v: 'KP', d: 'Keypoint number' }] },
  'LSEL.Item': { desc: 'Select lines by (LOC tests the line midpoint)', choices: [{ v: 'LOC', d: 'Midpoint location' }, { v: 'LINE', d: 'Line number' }, { v: 'LENGTH', d: 'Length' }, { v: 'RADIUS', d: 'Arc radius' }, { v: 'TYPE', d: 'LATT type' }, { v: 'MAT', d: 'LATT material' }] },
  'ASEL.Item': { desc: 'Select areas by (LOC tests the centroid)', choices: [{ v: 'LOC', d: 'Centroid location' }, { v: 'AREA', d: 'Area number' }, { v: 'EXT', d: 'Exterior areas of volumes' }, { v: 'TYPE', d: 'AATT type' }, { v: 'MAT', d: 'AATT material' }] },
  'VSEL.Item': { desc: 'Select volumes by (LOC tests the centroid)', choices: [{ v: 'LOC', d: 'Centroid location' }, { v: 'VOLU', d: 'Volume number' }, { v: 'TYPE', d: 'VATT type' }, { v: 'MAT', d: 'VATT material' }] },
  'NSLA.Type': { desc: 'Selection type', choices: SEL_TYPE_SHORT },
  'NSLV.Type': { desc: 'Selection type', choices: SEL_TYPE_SHORT },
  'NSLL.Type': { desc: 'Selection type', choices: SEL_TYPE_SHORT },
  'NSLK.Type': { desc: 'Selection type', choices: SEL_TYPE_SHORT },
  'ALLSEL.LabT': { desc: 'ALL = everything, BELOW = lower entities of the selection', choices: [{ v: 'ALL', d: 'Select everything (default)' }, { v: 'BELOW', d: 'Select entities below the selected ones' }] },
  'CM.Cname': { desc: 'Component name for the CURRENT selection' },
  'CM.Entity': { desc: 'Which selected entities to store', choices: ENTITIES },
  'CMSEL.Type': { desc: 'Selection type', choices: SEL_TYPE_SHORT.concat([{ v: 'ALL', d: 'All components' }, { v: 'NONE', d: 'Unselect all components' }]) },
  'CMSEL.Name': { desc: 'Component name' },
  // loads
  'D.NODE': { desc: `Node, ${ENTITY_LIST} — usually ALL after NSEL` },
  'D.Lab': { desc: 'DOF to constrain', choices: DOFS },
  'D.VALUE': { desc: 'Imposed value (blank / 0 = fixed)' },
  'D.Lab2': { desc: 'Extra DOF label', choices: DOFS },
  'DK.Lab': { desc: 'DOF to constrain', choices: DOFS },
  'DL.Lab': { desc: 'DOF to constrain', choices: DOFS.concat([{ v: 'SYMM', d: 'Symmetry' }, { v: 'ASYM', d: 'Antisymmetry' }]) },
  'DL.AREA': { desc: 'Area containing the line (for SYMM/ASYM)' },
  'DA.Lab': { desc: 'DOF to constrain', choices: DOFS.concat([{ v: 'SYMM', d: 'Symmetry' }, { v: 'ASYM', d: 'Antisymmetry' }]) },
  'DL.Value1': { desc: 'Constraint value (0 = fixed)' },
  'DA.Value1': { desc: 'Constraint value (0 = fixed)' },
  'F.Lab': { desc: 'Force or moment', choices: FORCES },
  'F.VALUE': { desc: 'Force value (sign = direction)' },
  'FK.Lab': { desc: 'Force or moment', choices: FORCES },
  'SFA.LKEY': { desc: 'Load key (blank / 1)' },
  'SFA.Lab': { desc: 'Surface load', choices: [{ v: 'PRES', d: 'Pressure (positive = into the surface)' }] },
  'SFE.LKEY': { desc: 'Element face number' },
  'SFE.Lab': { desc: 'Surface load', choices: [{ v: 'PRES', d: 'Pressure' }] },
  'ACEL.ACEL_X': { desc: 'Acceleration X' },
  'ACEL.ACEL_Y': { desc: 'Acceleration Y' },
  'ACEL.ACEL_Z': { desc: 'Acceleration Z: +9.81 makes gravity act in -Z' },
  // control & params
  '*DO.Par': { desc: 'Loop parameter name' },
  '*DO.IVAL': { desc: 'Start value' },
  '*DO.FVAL': { desc: 'Final value (inclusive)' },
  '*DO.INC': { desc: 'Increment (default 1)' },
  '*IF.VAL1': { desc: 'First value' },
  '*IF.Oper1': { desc: 'Comparison', choices: [{ v: 'EQ', d: 'Equal' }, { v: 'NE', d: 'Not equal' }, { v: 'LT', d: 'Less than' }, { v: 'GT', d: 'Greater than' }, { v: 'LE', d: 'Less or equal' }, { v: 'GE', d: 'Greater or equal' }, { v: 'ABLT', d: '|VAL1| < |VAL2|' }, { v: 'ABGT', d: '|VAL1| > |VAL2|' }] },
  '*IF.VAL2': { desc: 'Second value' },
  '*IF.Base1': { desc: 'Action', choices: [{ v: 'THEN', d: 'Block IF (close with *ENDIF)' }, { v: 'EXIT', d: 'Leave the *DO loop' }, { v: 'CYCLE', d: 'Skip to the next loop iteration' }, { v: 'AND', d: 'Combine with a second condition' }, { v: 'OR', d: 'Either condition' }] },
  '*GET.Par': { desc: 'Parameter to store the value in' },
  '*GET.Entity': { desc: 'Entity to query', choices: [{ v: 'KP', d: 'Keypoints' }, { v: 'LINE', d: 'Lines' }, { v: 'AREA', d: 'Areas' }, { v: 'VOLU', d: 'Volumes' }, { v: 'NODE', d: 'Nodes' }, { v: 'ELEM', d: 'Elements' }, { v: 'ACTIVE', d: 'Active settings (CSYS, TYPE ...)' }] },
  '*GET.ENTNUM': { desc: '0 = all selected (with COUNT / NUM), or a specific entity number' },
  '*GET.Item1': { desc: 'Item', choices: [{ v: 'COUNT', d: 'Number selected (ENTNUM 0)' }, { v: 'NUM', d: 'Number: then MAX / MIN (ENTNUM 0)' }, { v: 'LOC', d: 'Location: then X / Y / Z' }, { v: 'VOLU', d: 'Volume of a volume' }, { v: 'AREA', d: 'Area of an area' }, { v: 'LENG', d: 'Length of a line' }, { v: 'ATTR', d: 'Attribute: TYPE / MAT / REAL / SECN' }] },
  '*GET.IT1NUM': { desc: 'Item qualifier', choices: [{ v: 'MAX', d: 'Highest selected number' }, { v: 'MIN', d: 'Lowest selected number' }, { v: 'X', d: 'X' }, { v: 'Y', d: 'Y' }, { v: 'Z', d: 'Z' }] },
  '*SET.Par': { desc: 'Parameter name (NAME = value is the shorthand)' },
  '/PNUM.Label': { desc: 'What to number or colour by', choices: PNUM_LABELS },
  '/PNUM.KEY': { desc: '0 = off, 1 = on' },
  '/ESHAPE.SCALE': { desc: '1 = show beam/shell cross-sections, 0 = lines' },
  'CSYS.KCN': { desc: 'Active coordinate system', choices: [{ v: '0', d: 'Global Cartesian' }, { v: '1', d: 'Global cylindrical (R, θ, Z)' }, { v: '2', d: 'Global spherical' }, { v: '4', d: 'Working plane' }] },
  'SOLVE.Action': { desc: 'Blank (the trainer only runs model checks)' },
  'ANTYPE.Antype': { desc: 'Analysis type', choices: [{ v: 'STATIC', d: 'Static' }, { v: 'MODAL', d: 'Modal' }, { v: 'HARMIC', d: 'Harmonic' }, { v: 'TRANS', d: 'Transient' }] },
};

const NODE_LETTERS = 'IJKLMNOP';

function numbered(cmd: string, arg: string): ArgDoc | undefined {
  if ((cmd === 'E' || cmd === 'EN') && arg.length === 1 && NODE_LETTERS.includes(arg)) {
    const k = NODE_LETTERS.indexOf(arg);
    return { desc: `Node ${arg}${k >= 4 ? ` (top face, above ${NODE_LETTERS[k - 4]})` : k === 0 ? ' (uses the active TYPE, MAT, REAL, SECNUM)' : ''}` };
  }
  const m = /^([A-Za-z_]+?)(\d+)$/.exec(arg);
  if (!m) return undefined;
  const [, base, nStr] = m;
  const n = Number(nStr);
  switch (base) {
    case 'P': return { desc: `Keypoint ${n}${cmd === 'V' ? (n <= 4 ? ' (bottom face)' : ' (top face, above P' + (n - 4) + ')') : ''}` };
    case 'L': return { desc: `Line ${n} of the loop` };
    case 'A': return { desc: `Area ${n} bounding the volume` };
    case 'NA': return { desc: `Area ${n}${n === 1 ? `, ${ENTITY_LIST}` : ''}` };
    case 'NV': return { desc: `Volume ${n}${n === 1 ? `, ${ENTITY_LIST}` : ''}` };
    case 'NL': return { desc: `Line ${n}${n === 1 ? `, ${ENTITY_LIST}` : ''}` };
    case 'NLP': return { desc: `Path line ${n} (drag direction)` };
    case 'R': return { desc: `Real constant ${n}` };
    case 'KOP': return { desc: `KEYOPT(${n}) value` };
    case 'VAL': return { desc: `Value ${n}` };
    case 'Lab': return { desc: 'Extra DOF label', choices: DOFS };
    case 'C': return { desc: `Temperature coefficient C${n}` };
    case 'Item': return { desc: `Item ${n}` };
    case 'IT': return { desc: 'Item qualifier' };
    case 'Value': return { desc: n === 1 ? 'Value' : 'Second value' };
    case 'OFFSET': return { desc: `Offset ${n}` };
    case 'X': return { desc: `X of point ${n}` };
    case 'Y': return { desc: `Y of point ${n}` };
    case 'Z': return { desc: `Z of point ${n}` };
  }
  return undefined;
}

export function argDoc(cmd: string, arg: string): ArgDoc | undefined {
  return OVERRIDES[`${cmd}.${arg}`] ?? GENERIC[arg] ?? numbered(cmd, arg);
}
